// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szdlxvbdejatvezjjnyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6ZGx4dmJkZWphdHZlempqbnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1ODE1NzQsImV4cCI6MjA2OTE1NzU3NH0.xYJFwaTutM2L8fZHK4oOuB-7mqnVNW9oAXnadKLmLkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});